# Bump project version numbers, build ModManager.dll, and draft a release with notes from CHANGELOG.md
name: Draft Release
run-name: Draft Release (${{ inputs.bump_size }})

on:
  workflow_dispatch:
    inputs:
      bump_size:
        description: "Amount to bump version by"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      metadata_path: ModManager/Metadata.cs

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install semver tool
      run: |
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver

    - name: Retrieve current version
      run: echo "old_version=$(grep -o -E '[0-9]+\.[0-9]+\.[0-9]+' ${{ env.metadata_path }})" >> $GITHUB_ENV

    - name: Bump current version
      run: echo "new_version=$(semver bump ${{ inputs.bump_size }} ${{ env.old_version }})" >> $GITHUB_ENV

    - name: Bump metadata
      run: sed -i "s/${{ env.old_version }}/${{ env.new_version }}/" ${{ env.metadata_path }}

    - name: Bump CHANGELOG.md
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        tag: v${{ env.new_version }}

    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com

    - name: Commit and push
      run: |
        git add CHANGELOG.md ${{ env.metadata_path }}
        git commit -m "bump: v${{ env.old_version }} → v${{ env.new_version }}"
        git tag -a v${{ env.new_version }} -m "Automatic release tag"
        git push origin main --tags

    outputs:
      old_version: ${{ env.old_version }}
      new_version: ${{ env.new_version }}

  build:
    needs: [bump]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main # Override workflow SHA, so checkout includes bump commit

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      with:
        dotnet-version: 7.x

    - name: Install SpiderHeck assemblies
      run: |
        dotnet lib/DepotDownloader/DepotDownloader.dll -app 1329500 -depot 1329501 -manifest 7453118592264273764 -os windows -osarch 64 -username ${{ secrets.STEAM_USERNAME }} -password ${{ secrets.STEAM_PASSWORD }} -filelist game_assemblies.txt -dir SpiderHeck
        mkdir -p ModManager/lib
        mv SpiderHeck/SpiderHeckApp_Data/Managed/* ModManager/lib

    - name: Publish
      run: dotnet publish -c Release -p:PublishDir=../artifacts

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ModManager-${{ needs.bump.outputs.new_version }}
        path: artifacts/ModManager.dll
        if-no-files-found: error

  release:
    needs: [bump, build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main # Override workflow SHA, so checkout includes bump commit

    - name: Extract release notes
      id: extract_release_notes
      uses: ffurrer2/extract-release-notes@v1

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ModManager-${{ needs.bump.outputs.new_version }}
        path: artifacts/BepInEx/plugins

    - name: Compress artifact
      run: (cd artifacts && zip -r ModManager.zip BepInEx)

    - name: Draft release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: ${{ steps.extract_release_notes.outputs.release_notes }}
        tag: v${{ needs.bump.outputs.new_version }}
        artifacts: artifacts/ModManager.zip
        artifactErrorsFailBuild: true
        draft: true
